
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 07 23:23:33 CST 2013
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class SymFun {
  /* terminals */
  public static final int tminus = 32;
  public static final int tdecimal = 60;
  public static final int tigual = 45;
  public static final int tcase = 18;
  public static final int tvar = 5;
  public static final int tmas = 34;
  public static final int tor = 56;
  public static final int treturn = 64;
  public static final int tcc = 50;
  public static final int tpor = 36;
  public static final int tif = 13;
  public static final int tca = 49;
  public static final int tmenorigual = 41;
  public static final int tpasentero = 25;
  public static final int tdividir = 37;
  public static final int tbool = 10;
  public static final int tcadena = 63;
  public static final int tlc = 52;
  public static final int tcall = 29;
  public static final int tla = 51;
  public static final int tmenos = 35;
  public static final int tmenor = 39;
  public static final int tdefault = 19;
  public static final int tswitch = 17;
  public static final int tint = 7;
  public static final int tthis = 30;
  public static final int tbreak = 20;
  public static final int tfor = 15;
  public static final int tmayorigual = 42;
  public static final int tmayor = 40;
  public static final int ttrue = 21;
  public static final int tand = 57;
  public static final int tcoma = 55;
  public static final int tmayus = 33;
  public static final int tpasfloat = 26;
  public static final int tfun = 4;
  public static final int tpunto = 54;
  public static final int tuse = 3;
  public static final int EOF = 0;
  public static final int tno = 58;
  public static final int twhile = 16;
  public static final int tvoid = 12;
  public static final int error = 1;
  public static final int timprimir = 28;
  public static final int tstring = 9;
  public static final int tfloat = 8;
  public static final int telse = 14;
  public static final int tvalue = 31;
  public static final int tiden = 61;
  public static final int tfalse = 22;
  public static final int tigualigual = 43;
  public static final int tas = 6;
  public static final int tdospuntos = 53;
  public static final int tcaracter = 62;
  public static final int tnombre = 2;
  public static final int tconcat = 38;
  public static final int tentero = 59;
  public static final int tdiferente = 44;
  public static final int tarchivo = 24;
  public static final int tpuntocoma = 46;
  public static final int tpasstring = 27;
  public static final int tdel = 23;
  public static final int tpc = 48;
  public static final int tpa = 47;
  public static final int tchar = 11;
}

