
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Mar 22 13:53:33 CST 2014
//----------------------------------------------------

package analisis;

import java_cup.runtime.*;
import java.util.*;

/** CUP v0.10k generated parser.
  * @version Sat Mar 22 13:53:33 CST 2014
  */
public class ServidorAParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ServidorAParser() {super();}

  /** Constructor which sets the default scanner. */
  public ServidorAParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\116\000\002\002\004\000\002\003\003\000\002\004" +
    "\003\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\006\007\000\002\007\004\000\002" +
    "\007\003\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\010\005\000\002\010\005\000\002\011\004" +
    "\000\002\011\003\000\002\012\005\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\005\000\002\012\005\000\002\012\005" +
    "\000\002\012\003\000\002\012\003\000\002\012\003\000" +
    "\002\013\005\000\002\014\004\000\002\014\003\000\002" +
    "\015\005\000\002\016\005\000\002\017\004\000\002\017" +
    "\002\000\002\020\007\000\002\021\004\000\002\021\003" +
    "\000\002\022\005\000\002\022\005\000\002\023\004\000" +
    "\002\023\003\000\002\024\007\000\002\025\004\000\002" +
    "\025\003\000\002\026\005\000\002\026\005\000\002\026" +
    "\005\000\002\026\005\000\002\026\005\000\002\027\003" +
    "\000\002\027\003\000\002\027\002\000\002\030\005\000" +
    "\002\031\003\000\002\036\006\000\002\032\005\000\002" +
    "\033\004\000\002\033\003\000\002\041\011\000\002\042" +
    "\004\000\002\042\003\000\002\043\005\000\002\034\007" +
    "\000\002\035\005\000\002\037\005\000\002\040\006\000" +
    "\002\044\006\000\002\045\004\000\002\045\003\000\002" +
    "\046\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\256\000\020\004\015\036\016\040\023\050\006\052" +
    "\024\074\004\105\012\001\002\000\004\102\246\001\002" +
    "\000\004\002\uffff\001\002\000\004\071\243\001\002\000" +
    "\004\002\ufffb\001\002\000\004\002\242\001\002\000\004" +
    "\002\ufffc\001\002\000\004\071\231\001\002\000\004\002" +
    "\000\001\002\000\004\002\ufffd\001\002\000\014\054\206" +
    "\056\207\057\211\060\212\061\210\001\002\000\004\006" +
    "\174\001\002\000\004\002\ufffa\001\002\000\004\002\ufffe" +
    "\001\002\000\004\002\ufff9\001\002\000\004\002\ufff8\001" +
    "\002\000\036\006\031\010\044\012\037\014\034\016\041" +
    "\020\033\022\046\024\030\026\045\042\032\044\040\046" +
    "\043\100\047\103\036\001\002\000\036\006\031\010\044" +
    "\012\037\014\034\016\041\020\033\022\046\024\030\026" +
    "\045\042\032\044\040\046\043\100\047\103\036\001\002" +
    "\000\056\005\uffe1\006\uffe1\010\uffe1\012\uffe1\014\uffe1\016" +
    "\uffe1\020\uffe1\022\uffe1\024\uffe1\026\uffe1\041\uffe1\042\uffe1" +
    "\044\uffe1\046\uffe1\047\uffe1\051\uffe1\053\uffe1\070\uffe1\077" +
    "\uffe1\100\uffe1\103\uffe1\110\uffe1\001\002\000\040\006\031" +
    "\010\044\012\037\014\034\016\041\020\033\022\046\024" +
    "\030\026\045\042\032\044\040\046\043\053\170\100\047" +
    "\103\036\001\002\000\056\005\uffdf\006\uffdf\010\uffdf\012" +
    "\uffdf\014\uffdf\016\uffdf\020\uffdf\022\uffdf\024\uffdf\026\uffdf" +
    "\041\uffdf\042\uffdf\044\uffdf\046\uffdf\047\uffdf\051\uffdf\053" +
    "\uffdf\070\uffdf\077\uffdf\100\uffdf\103\uffdf\110\uffdf\001\002" +
    "\000\006\025\uffd8\030\uffd8\001\002\000\004\071\110\001" +
    "\002\000\004\071\106\001\002\000\004\071\104\001\002" +
    "\000\004\071\102\001\002\000\056\005\uffee\006\uffee\010" +
    "\uffee\012\uffee\014\uffee\016\uffee\020\uffee\022\uffee\024\uffee" +
    "\026\uffee\041\uffee\042\uffee\044\uffee\046\uffee\047\uffee\051" +
    "\uffee\053\uffee\070\uffee\077\uffee\100\uffee\103\uffee\110\uffee" +
    "\001\002\000\004\071\100\001\002\000\004\071\076\001" +
    "\002\000\004\071\074\001\002\000\004\071\072\001\002" +
    "\000\056\005\uffe0\006\uffe0\010\uffe0\012\uffe0\014\uffe0\016" +
    "\uffe0\020\uffe0\022\uffe0\024\uffe0\026\uffe0\041\uffe0\042\uffe0" +
    "\044\uffe0\046\uffe0\047\uffe0\051\uffe0\053\uffe0\070\uffe0\077" +
    "\uffe0\100\uffe0\103\uffe0\110\uffe0\001\002\000\004\071\065" +
    "\001\002\000\004\073\063\001\002\000\004\071\061\001" +
    "\002\000\004\026\052\001\002\000\004\071\050\001\002" +
    "\000\004\101\051\001\002\000\056\005\uffe5\006\uffe5\010" +
    "\uffe5\012\uffe5\014\uffe5\016\uffe5\020\uffe5\022\uffe5\024\uffe5" +
    "\026\uffe5\041\uffe5\042\uffe5\044\uffe5\046\uffe5\047\uffe5\051" +
    "\uffe5\053\uffe5\070\uffe5\077\uffe5\100\uffe5\103\uffe5\110\uffe5" +
    "\001\002\000\004\071\057\001\002\000\006\023\uffdc\026" +
    "\uffdc\001\002\000\006\023\056\026\052\001\002\000\006" +
    "\023\uffdd\026\uffdd\001\002\000\056\005\uffde\006\uffde\010" +
    "\uffde\012\uffde\014\uffde\016\uffde\020\uffde\022\uffde\024\uffde" +
    "\026\uffde\041\uffde\042\uffde\044\uffde\046\uffde\047\uffde\051" +
    "\uffde\053\uffde\070\uffde\077\uffde\100\uffde\103\uffde\110\uffde" +
    "\001\002\000\004\027\060\001\002\000\006\023\uffdb\026" +
    "\uffdb\001\002\000\004\027\062\001\002\000\056\005\uffe2" +
    "\006\uffe2\010\uffe2\012\uffe2\014\uffe2\016\uffe2\020\uffe2\022" +
    "\uffe2\024\uffe2\026\uffe2\041\uffe2\042\uffe2\044\uffe2\046\uffe2" +
    "\047\uffe2\051\uffe2\053\uffe2\070\uffe2\077\uffe2\100\uffe2\103" +
    "\uffe2\110\uffe2\001\002\000\004\011\064\001\002\000\056" +
    "\005\uffec\006\uffec\010\uffec\012\uffec\014\uffec\016\uffec\020" +
    "\uffec\022\uffec\024\uffec\026\uffec\041\uffec\042\uffec\044\uffec" +
    "\046\uffec\047\uffec\051\uffec\053\uffec\070\uffec\077\uffec\100" +
    "\uffec\103\uffec\110\uffec\001\002\000\040\006\031\010\044" +
    "\012\037\014\034\016\041\020\033\022\046\024\030\026" +
    "\045\042\032\044\040\046\043\047\067\100\047\103\036" +
    "\001\002\000\040\006\031\010\044\012\037\014\034\016" +
    "\041\020\033\022\046\024\030\026\045\042\032\044\040" +
    "\046\043\047\071\100\047\103\036\001\002\000\056\005" +
    "\uffe6\006\uffe6\010\uffe6\012\uffe6\014\uffe6\016\uffe6\020\uffe6" +
    "\022\uffe6\024\uffe6\026\uffe6\041\uffe6\042\uffe6\044\uffe6\046" +
    "\uffe6\047\uffe6\051\uffe6\053\uffe6\070\uffe6\077\uffe6\100\uffe6" +
    "\103\uffe6\110\uffe6\001\002\000\056\005\uffef\006\uffef\010" +
    "\uffef\012\uffef\014\uffef\016\uffef\020\uffef\022\uffef\024\uffef" +
    "\026\uffef\041\uffef\042\uffef\044\uffef\046\uffef\047\uffef\051" +
    "\uffef\053\uffef\070\uffef\077\uffef\100\uffef\103\uffef\110\uffef" +
    "\001\002\000\056\005\uffc3\006\uffc3\010\uffc3\012\uffc3\014" +
    "\uffc3\016\uffc3\020\uffc3\022\uffc3\024\uffc3\026\uffc3\041\uffc3" +
    "\042\uffc3\044\uffc3\046\uffc3\047\uffc3\051\uffc3\053\uffc3\070" +
    "\uffc3\077\uffc3\100\uffc3\103\uffc3\110\uffc3\001\002\000\004" +
    "\017\073\001\002\000\056\005\uffe8\006\uffe8\010\uffe8\012" +
    "\uffe8\014\uffe8\016\uffe8\020\uffe8\022\uffe8\024\uffe8\026\uffe8" +
    "\041\uffe8\042\uffe8\044\uffe8\046\uffe8\047\uffe8\051\uffe8\053" +
    "\uffe8\070\uffe8\077\uffe8\100\uffe8\103\uffe8\110\uffe8\001\002" +
    "\000\004\045\075\001\002\000\056\005\uffe3\006\uffe3\010" +
    "\uffe3\012\uffe3\014\uffe3\016\uffe3\020\uffe3\022\uffe3\024\uffe3" +
    "\026\uffe3\041\uffe3\042\uffe3\044\uffe3\046\uffe3\047\uffe3\051" +
    "\uffe3\053\uffe3\070\uffe3\077\uffe3\100\uffe3\103\uffe3\110\uffe3" +
    "\001\002\000\004\013\077\001\002\000\056\005\uffeb\006" +
    "\uffeb\010\uffeb\012\uffeb\014\uffeb\016\uffeb\020\uffeb\022\uffeb" +
    "\024\uffeb\026\uffeb\041\uffeb\042\uffeb\044\uffeb\046\uffeb\047" +
    "\uffeb\051\uffeb\053\uffeb\070\uffeb\077\uffeb\100\uffeb\103\uffeb" +
    "\110\uffeb\001\002\000\004\104\101\001\002\000\056\005" +
    "\uffe4\006\uffe4\010\uffe4\012\uffe4\014\uffe4\016\uffe4\020\uffe4" +
    "\022\uffe4\024\uffe4\026\uffe4\041\uffe4\042\uffe4\044\uffe4\046" +
    "\uffe4\047\uffe4\051\uffe4\053\uffe4\070\uffe4\077\uffe4\100\uffe4" +
    "\103\uffe4\110\uffe4\001\002\000\004\015\103\001\002\000" +
    "\056\005\uffea\006\uffea\010\uffea\012\uffea\014\uffea\016\uffea" +
    "\020\uffea\022\uffea\024\uffea\026\uffea\041\uffea\042\uffea\044" +
    "\uffea\046\uffea\047\uffea\051\uffea\053\uffea\070\uffea\077\uffea" +
    "\100\uffea\103\uffea\110\uffea\001\002\000\004\021\105\001" +
    "\002\000\056\005\uffe9\006\uffe9\010\uffe9\012\uffe9\014\uffe9" +
    "\016\uffe9\020\uffe9\022\uffe9\024\uffe9\026\uffe9\041\uffe9\042" +
    "\uffe9\044\uffe9\046\uffe9\047\uffe9\051\uffe9\053\uffe9\070\uffe9" +
    "\077\uffe9\100\uffe9\103\uffe9\110\uffe9\001\002\000\004\043" +
    "\107\001\002\000\056\005\uffe7\006\uffe7\010\uffe7\012\uffe7" +
    "\014\uffe7\016\uffe7\020\uffe7\022\uffe7\024\uffe7\026\uffe7\041" +
    "\uffe7\042\uffe7\044\uffe7\046\uffe7\047\uffe7\051\uffe7\053\uffe7" +
    "\070\uffe7\077\uffe7\100\uffe7\103\uffe7\110\uffe7\001\002\000" +
    "\004\007\111\001\002\000\056\005\uffed\006\uffed\010\uffed" +
    "\012\uffed\014\uffed\016\uffed\020\uffed\022\uffed\024\uffed\026" +
    "\uffed\041\uffed\042\uffed\044\uffed\046\uffed\047\uffed\051\uffed" +
    "\053\uffed\070\uffed\077\uffed\100\uffed\103\uffed\110\uffed\001" +
    "\002\000\006\025\114\030\115\001\002\000\006\025\uffd9" +
    "\030\uffd9\001\002\000\056\005\uffda\006\uffda\010\uffda\012" +
    "\uffda\014\uffda\016\uffda\020\uffda\022\uffda\024\uffda\026\uffda" +
    "\041\uffda\042\uffda\044\uffda\046\uffda\047\uffda\051\uffda\053" +
    "\uffda\070\uffda\077\uffda\100\uffda\103\uffda\110\uffda\001\002" +
    "\000\006\054\121\055\116\001\002\000\004\067\166\001" +
    "\002\000\010\054\121\055\116\071\125\001\002\000\010" +
    "\054\uffd5\055\uffd5\071\uffd5\001\002\000\004\067\122\001" +
    "\002\000\004\072\123\001\002\000\010\054\uffd4\055\uffd4" +
    "\071\uffd4\001\002\000\010\054\uffd6\055\uffd6\071\uffd6\001" +
    "\002\000\004\032\126\001\002\000\014\054\137\062\134" +
    "\063\133\064\140\065\141\001\002\000\006\031\132\032" +
    "\126\001\002\000\006\031\uffd1\032\uffd1\001\002\000\006" +
    "\031\uffd2\032\uffd2\001\002\000\006\025\uffd7\030\uffd7\001" +
    "\002\000\004\067\164\001\002\000\004\067\162\001\002" +
    "\000\016\054\137\062\134\063\133\064\140\065\141\071" +
    "\151\001\002\000\016\054\uffce\062\uffce\063\uffce\064\uffce" +
    "\065\uffce\071\uffce\001\002\000\004\067\146\001\002\000" +
    "\004\067\144\001\002\000\004\067\142\001\002\000\004" +
    "\072\143\001\002\000\016\054\uffc9\062\uffc9\063\uffc9\064" +
    "\uffc9\065\uffc9\071\uffc9\001\002\000\004\072\145\001\002" +
    "\000\016\054\uffca\062\uffca\063\uffca\064\uffca\065\uffca\071" +
    "\uffca\001\002\000\004\072\147\001\002\000\016\054\uffcb" +
    "\062\uffcb\063\uffcb\064\uffcb\065\uffcb\071\uffcb\001\002\000" +
    "\016\054\uffcf\062\uffcf\063\uffcf\064\uffcf\065\uffcf\071\uffcf" +
    "\001\002\000\010\033\uffc6\034\154\072\152\001\002\000" +
    "\004\033\uffc8\001\002\000\004\033\uffc7\001\002\000\004" +
    "\066\157\001\002\000\004\033\156\001\002\000\006\031" +
    "\uffd0\032\uffd0\001\002\000\004\035\uffc4\001\002\000\004" +
    "\035\161\001\002\000\004\033\uffc5\001\002\000\004\072" +
    "\163\001\002\000\016\054\uffcd\062\uffcd\063\uffcd\064\uffcd" +
    "\065\uffcd\071\uffcd\001\002\000\004\072\165\001\002\000" +
    "\016\054\uffcc\062\uffcc\063\uffcc\064\uffcc\065\uffcc\071\uffcc" +
    "\001\002\000\004\072\167\001\002\000\010\054\uffd3\055" +
    "\uffd3\071\uffd3\001\002\000\004\002\uffb9\001\002\000\040" +
    "\006\031\010\044\012\037\014\034\016\041\020\033\022" +
    "\046\024\030\026\045\041\172\042\032\044\040\046\043" +
    "\100\047\103\036\001\002\000\004\002\uffba\001\002\000" +
    "\006\006\uffc0\037\uffc0\001\002\000\004\071\200\001\002" +
    "\000\006\006\174\037\177\001\002\000\006\006\uffc1\037" +
    "\uffc1\001\002\000\004\002\uffc2\001\002\000\036\006\031" +
    "\010\044\012\037\014\034\016\041\020\033\022\046\024" +
    "\030\026\045\042\032\044\040\046\043\100\047\103\036" +
    "\001\002\000\040\006\031\010\044\012\037\014\034\016" +
    "\041\020\033\022\046\024\030\026\045\042\032\044\040" +
    "\046\043\070\202\100\047\103\036\001\002\000\004\007" +
    "\203\001\002\000\006\006\uffbb\037\uffbb\001\002\000\016" +
    "\054\206\056\207\057\211\060\212\061\210\071\226\001" +
    "\002\000\016\054\ufff5\056\ufff5\057\ufff5\060\ufff5\061\ufff5" +
    "\071\ufff5\001\002\000\004\067\223\001\002\000\004\067" +
    "\221\001\002\000\004\067\217\001\002\000\004\067\215" +
    "\001\002\000\004\067\213\001\002\000\004\072\214\001" +
    "\002\000\016\054\ufff1\056\ufff1\057\ufff1\060\ufff1\061\ufff1" +
    "\071\ufff1\001\002\000\004\072\216\001\002\000\016\054" +
    "\ufff2\056\ufff2\057\ufff2\060\ufff2\061\ufff2\071\ufff2\001\002" +
    "\000\004\072\220\001\002\000\016\054\ufff0\056\ufff0\057" +
    "\ufff0\060\ufff0\061\ufff0\071\ufff0\001\002\000\004\072\222" +
    "\001\002\000\016\054\ufff3\056\ufff3\057\ufff3\060\ufff3\061" +
    "\ufff3\071\ufff3\001\002\000\004\072\224\001\002\000\016" +
    "\054\ufff4\056\ufff4\057\ufff4\060\ufff4\061\ufff4\071\ufff4\001" +
    "\002\000\016\054\ufff6\056\ufff6\057\ufff6\060\ufff6\061\ufff6" +
    "\071\ufff6\001\002\000\036\006\031\010\044\012\037\014" +
    "\034\016\041\020\033\022\046\024\030\026\045\042\032" +
    "\044\040\046\043\100\047\103\036\001\002\000\040\005" +
    "\230\006\031\010\044\012\037\014\034\016\041\020\033" +
    "\022\046\024\030\026\045\042\032\044\040\046\043\100" +
    "\047\103\036\001\002\000\004\002\ufff7\001\002\000\004" +
    "\107\233\001\002\000\006\106\240\107\233\001\002\000" +
    "\004\071\235\001\002\000\006\106\uffb5\107\uffb5\001\002" +
    "\000\036\006\031\010\044\012\037\014\034\016\041\020" +
    "\033\022\046\024\030\026\045\042\032\044\040\046\043" +
    "\100\047\103\036\001\002\000\040\006\031\010\044\012" +
    "\037\014\034\016\041\020\033\022\046\024\030\026\045" +
    "\042\032\044\040\046\043\100\047\103\036\110\237\001" +
    "\002\000\006\106\uffb4\107\uffb4\001\002\000\004\002\uffb7" +
    "\001\002\000\006\106\uffb6\107\uffb6\001\002\000\004\002" +
    "\001\001\002\000\036\006\031\010\044\012\037\014\034" +
    "\016\041\020\033\022\046\024\030\026\045\042\032\044" +
    "\040\046\043\100\047\103\036\001\002\000\040\006\031" +
    "\010\044\012\037\014\034\016\041\020\033\022\046\024" +
    "\030\026\045\042\032\044\040\046\043\051\245\100\047" +
    "\103\036\001\002\000\004\002\uffb8\001\002\000\004\067" +
    "\247\001\002\000\004\072\250\001\002\000\004\071\251" +
    "\001\002\000\004\076\252\001\002\000\036\006\031\010" +
    "\044\012\037\014\034\016\041\020\033\022\046\024\030" +
    "\026\045\042\032\044\040\046\043\100\047\103\036\001" +
    "\002\000\006\075\256\076\252\001\002\000\006\075\uffbd" +
    "\076\uffbd\001\002\000\006\075\uffbe\076\uffbe\001\002\000" +
    "\004\002\uffbf\001\002\000\040\006\031\010\044\012\037" +
    "\014\034\016\041\020\033\022\046\024\030\026\045\042" +
    "\032\044\040\046\043\077\260\100\047\103\036\001\002" +
    "\000\006\075\uffbc\076\uffbc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\256\000\026\003\007\004\012\005\004\006\017\032" +
    "\013\035\010\037\016\040\006\041\020\044\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\203\010\204\001\001\000\006\033\174\034\172\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\011\170\012\034\013\024\016\041" +
    "\036\026\001\001\000\014\011\025\012\034\013\024\016" +
    "\041\036\026\001\001\000\002\001\001\000\012\012\067" +
    "\013\024\016\041\036\026\001\001\000\002\001\001\000" +
    "\004\017\111\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\014\053\015\052\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\054\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\011\065\012\034\013" +
    "\024\016\041\036\026\001\001\000\012\012\067\013\024" +
    "\016\041\036\026\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\112\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\021\116\022\117\001\001" +
    "\000\002\001\001\000\004\022\123\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\023\126\024\127\001\001\000" +
    "\006\025\134\026\135\001\001\000\004\024\130\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\026\147\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\027\154\030\152\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\031\157\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\012" +
    "\067\013\024\016\041\036\026\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\034\175\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\011\200" +
    "\012\034\013\024\016\041\036\026\001\001\000\012\012" +
    "\067\013\024\016\041\036\026\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\010\224\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\011\226\012\034\013\024\016\041\036\026\001" +
    "\001\000\012\012\067\013\024\016\041\036\026\001\001" +
    "\000\002\001\001\000\006\045\231\046\233\001\001\000" +
    "\004\046\240\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\011\235\012\034\013\024\016\041\036\026\001" +
    "\001\000\012\012\067\013\024\016\041\036\026\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\011\243\012\034\013\024\016\041" +
    "\036\026\001\001\000\012\012\067\013\024\016\041\036" +
    "\026\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\042\252\043\253\001" +
    "\001\000\014\011\256\012\034\013\024\016\041\036\026" +
    "\001\001\000\004\043\254\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\012\067\013\024" +
    "\016\041\036\026\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ServidorAParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ServidorAParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ServidorAParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automaticamente ante algun error sintáctico.*/
    public void syntax_error(Symbol s)
    {
        //Metodos.addError("sintactico", (s.right+1), s.left, "Identificador \"" +s.value + "\" no reconocido por la gramatica");
        System.out.println("Error sintactico en la Fila " + (s.right+1) +" Columna "+s.left+ ". Identificador \"" +s.value + "\" no reconocido." );
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    { 
        //Metodos.addError("sintactico", (s.right+1), s.left, "Identificador \"" +s.value + "\" no reconocido por la gramatica");
        System.out.println("Error sintactico en la Fila " + (s.right+1)+ " Columna "+s.left+". Identificador \"" + s.value + "\" no reconocido."); 
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ServidorAParser$actions {


    int nvl = 0;
    String nombreArchivo ="";

  private final ServidorAParser parser;

  /** Constructor */
  CUP$ServidorAParser$actions(ServidorAParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ServidorAParser$do_action(
    int                        CUP$ServidorAParser$act_num,
    java_cup.runtime.lr_parser CUP$ServidorAParser$parser,
    java.util.Stack            CUP$ServidorAParser$stack,
    int                        CUP$ServidorAParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ServidorAParser$result;

      /* select the action based on the action number */
      switch (CUP$ServidorAParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // SOLICITUD ::= tssolicitud tcadcampo LISTA_CAMPOS tesolicitud 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(36/*SOLICITUD*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // LISTA_SOLICITUDES ::= SOLICITUD 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(35/*LISTA_SOLICITUDES*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // LISTA_SOLICITUDES ::= LISTA_SOLICITUDES SOLICITUD 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(35/*LISTA_SOLICITUDES*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // SOLICITUDES ::= tssolicitudes tcadcampo LISTA_SOLICITUDES tesolicitudes 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(34/*SOLICITUDES*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // SOLICITUD_AMISTAD ::= tssolicitudamistad tcadcampo LISTA_CAMPOS tesolicitudamistad 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(30/*SOLICITUD_AMISTAD*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // MENSAJE ::= tsmensaje LISTA_CAMPOS temensaje 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(29/*MENSAJE*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // LOGIN ::= tslogin LISTA_CAMPOS telogin 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(27/*LOGIN*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // USUARIO ::= tsusuario tcadcampo LISTA_CAMPOS tmenor teusuario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(26/*USUARIO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // CORREO ::= tscorreo LISTA_CAMPOS tecorreo 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(33/*CORREO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // LISTA_CORREOS ::= CORREO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(32/*LISTA_CORREOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // LISTA_CORREOS ::= LISTA_CORREOS CORREO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(32/*LISTA_CORREOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // CORREOS ::= tscorreos tusuario tigual tcadena tcadcampo LISTA_CORREOS tecorreos 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(31/*CORREOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // LISTA_USUARIOS ::= USUARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(25/*LISTA_USUARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // LISTA_USUARIOS ::= LISTA_USUARIOS USUARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(25/*LISTA_USUARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // USUARIOS ::= tsusuarios LISTA_USUARIOS teusuarios 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(24/*USUARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // EMISOR ::= tsemisor tcadcampo LISTA_CAMPOS teemisor 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(28/*EMISOR*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // INSTRUCCIONES ::= tinstrucciones 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(23/*INSTRUCCIONES*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // FORMULA ::= tsformula INSTRUCCIONES teformula 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(22/*FORMULA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // CONTENIDO_CELDA ::= 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(21/*CONTENIDO_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // CONTENIDO_CELDA ::= FORMULA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(21/*CONTENIDO_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // CONTENIDO_CELDA ::= tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(21/*CONTENIDO_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ATRIBUTOS_CELDA ::= tformula tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ATRIBUTOS_CELDA ::= tcolor tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ATRIBUTOS_CELDA ::= ttipo tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ATRIBUTOS_CELDA ::= tcolumna tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ATRIBUTOS_CELDA ::= tfila tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // LISTA_ATR_CELDA ::= ATRIBUTOS_CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(19/*LISTA_ATR_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // LISTA_ATR_CELDA ::= LISTA_ATR_CELDA ATRIBUTOS_CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(19/*LISTA_ATR_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // CELDA ::= tscelda LISTA_ATR_CELDA tcadcampo CONTENIDO_CELDA tecelda 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(18/*CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // LISTA_CELDAS ::= CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(17/*LISTA_CELDAS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // LISTA_CELDAS ::= LISTA_CELDAS CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(17/*LISTA_CELDAS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // ATRIBUTO_ARCHIVO ::= ttama tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(16/*ATRIBUTO_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // ATRIBUTO_ARCHIVO ::= ttipo tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(16/*ATRIBUTO_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // LISTA_ATR_ARCHIVO ::= ATRIBUTO_ARCHIVO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(15/*LISTA_ATR_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // LISTA_ATR_ARCHIVO ::= LISTA_ATR_ARCHIVO ATRIBUTO_ARCHIVO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(15/*LISTA_ATR_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // ARCHIVO ::= tsarchivo LISTA_ATR_ARCHIVO tcadcampo LISTA_CELDAS tearchivo 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(14/*ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // LISTA_ARCHIVOS ::= 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(13/*LISTA_ARCHIVOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // LISTA_ARCHIVOS ::= LISTA_ARCHIVOS ARCHIVO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(13/*LISTA_ARCHIVOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // ARCHIVOS ::= tsarchivos LISTA_ARCHIVOS tearchivos 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(12/*ARCHIVOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // DESTINATARIO ::= tsdestinatario tcadcampo tedestinatario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(11/*DESTINATARIO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // LISTA_DESTINATARIOS ::= DESTINATARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(10/*LISTA_DESTINATARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // LISTA_DESTINATARIOS ::= LISTA_DESTINATARIOS DESTINATARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(10/*LISTA_DESTINATARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // DESTINATARIOS ::= tsdestinatarios LISTA_DESTINATARIOS tedestinatarios 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(9/*DESTINATARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // CAMPOS ::= EMISOR 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // CAMPOS ::= ARCHIVOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // CAMPOS ::= DESTINATARIOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // CAMPOS ::= tsdestinatario tcadcampo tedestinatario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // CAMPOS ::= tsrespuesta tcadcampo terespuesta 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // CAMPOS ::= tsdestino tcadcampo tedestino 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // CAMPOS ::= tsde tcadcampo tede 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // CAMPOS ::= tsemisor tcadcampo teemisor 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // CAMPOS ::= tsestado tcadcampo teestado 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // CAMPOS ::= tsasunto tcadcampo teasunto 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // CAMPOS ::= tscontenido tcadcampo tecontenido 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // CAMPOS ::= tsclave tcadcampo teclave 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // CAMPOS ::= tsnombre tcadcampo tenombre 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // CAMPOS ::= tsfecha tfechacadena tefecha 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // CAMPOS ::= tsusuario tcadcampo teusuario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // LISTA_CAMPOS ::= CAMPOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(7/*LISTA_CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // LISTA_CAMPOS ::= LISTA_CAMPOS CAMPOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(7/*LISTA_CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ATRIBUTO_SESION ::= tfecha tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ATRIBUTO_SESION ::= tde tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ATRIBUTO_SESION ::= tpeticion tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ATRIBUTO_SESION ::= tid tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ATRIBUTO_SESION ::= ttipo tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // LISTA_ATR_SESION ::= ATRIBUTO_SESION 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(5/*LISTA_ATR_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // LISTA_ATR_SESION ::= LISTA_ATR_SESION ATRIBUTO_SESION 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(5/*LISTA_ATR_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SESION ::= tssesion LISTA_ATR_SESION tcadcampo LISTA_CAMPOS tesesion 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(4/*SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ELEMENTOS ::= SOLICITUDES 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ELEMENTOS ::= CORREOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ELEMENTOS ::= MENSAJE 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ELEMENTOS ::= SOLICITUD_AMISTAD 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // ELEMENTOS ::= LOGIN 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // ELEMENTOS ::= USUARIOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ELEMENTOS ::= SESION 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CUERPO ::= ELEMENTOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(2/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CUERPO 
            {
              Object RESULT = null;
		 System.out.println("Fin"); 
              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).value;
		RESULT = start_val;
              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$ServidorAParser$parser.done_parsing();
          return CUP$ServidorAParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

