
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 21 05:08:56 CST 2014
//----------------------------------------------------

package analisis;

import java_cup.runtime.*;
import java.util.*;

/** CUP v0.10k generated parser.
  * @version Fri Mar 21 05:08:56 CST 2014
  */
public class ServidorAParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ServidorAParser() {super();}

  /** Constructor which sets the default scanner. */
  public ServidorAParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\004\000\002\003\003\000\002\004" +
    "\003\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\006\007\000" +
    "\002\007\004\000\002\007\003\000\002\010\005\000\002" +
    "\010\005\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\011\004\000\002\011\003\000\002\012\005" +
    "\000\002\012\005\000\002\012\005\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\003\000\002\012\003\000\002\013" +
    "\005\000\002\014\004\000\002\014\003\000\002\015\005" +
    "\000\002\016\005\000\002\017\004\000\002\017\002\000" +
    "\002\020\007\000\002\021\004\000\002\021\003\000\002" +
    "\022\005\000\002\022\005\000\002\023\004\000\002\023" +
    "\003\000\002\024\007\000\002\025\004\000\002\025\003" +
    "\000\002\026\005\000\002\026\005\000\002\026\005\000" +
    "\002\026\005\000\002\026\005\000\002\027\003\000\002" +
    "\027\003\000\002\027\002\000\002\030\005\000\002\031" +
    "\003\000\002\036\007\000\002\032\005\000\002\033\004" +
    "\000\002\033\003\000\002\034\007\000\002\035\005\000" +
    "\002\040\005\000\002\041\005\000\002\037\005\000\002" +
    "\037\005\000\002\037\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\222\000\014\004\013\036\014\040\017\050\006\052" +
    "\020\001\002\000\004\002\ufffb\001\002\000\004\002\uffff" +
    "\001\002\000\010\026\207\044\210\046\211\001\002\000" +
    "\004\002\206\001\002\000\004\002\ufffc\001\002\000\004" +
    "\002\000\001\002\000\004\002\ufffd\001\002\000\014\054" +
    "\163\056\165\057\167\060\164\061\166\001\002\000\004" +
    "\006\151\001\002\000\004\002\ufffa\001\002\000\004\002" +
    "\ufffe\001\002\000\026\006\023\010\022\012\027\014\021" +
    "\016\031\020\035\022\026\024\033\042\034\046\024\001" +
    "\002\000\026\006\023\010\022\012\027\014\021\016\031" +
    "\020\035\022\026\024\033\042\034\046\024\001\002\000" +
    "\004\074\144\001\002\000\004\073\142\001\002\000\004" +
    "\074\140\001\002\000\004\074\136\001\002\000\036\005" +
    "\uffe7\006\uffe7\010\uffe7\012\uffe7\014\uffe7\016\uffe7\020\uffe7" +
    "\022\uffe7\024\uffe7\041\uffe7\042\uffe7\046\uffe7\053\uffe7\070" +
    "\uffe7\001\002\000\004\026\127\001\002\000\004\074\125" +
    "\001\002\000\036\005\uffe6\006\uffe6\010\uffe6\012\uffe6\014" +
    "\uffe6\016\uffe6\020\uffe6\022\uffe6\024\uffe6\041\uffe6\042\uffe6" +
    "\046\uffe6\053\uffe6\070\uffe6\001\002\000\004\074\123\001" +
    "\002\000\030\006\023\010\022\012\027\014\021\016\031" +
    "\020\035\022\026\024\033\042\034\046\024\053\121\001" +
    "\002\000\006\025\uffdf\030\uffdf\001\002\000\004\074\041" +
    "\001\002\000\004\074\037\001\002\000\036\005\ufff0\006" +
    "\ufff0\010\ufff0\012\ufff0\014\ufff0\016\ufff0\020\ufff0\022\ufff0" +
    "\024\ufff0\041\ufff0\042\ufff0\046\ufff0\053\ufff0\070\ufff0\001" +
    "\002\000\004\021\040\001\002\000\036\005\uffeb\006\uffeb" +
    "\010\uffeb\012\uffeb\014\uffeb\016\uffeb\020\uffeb\022\uffeb\024" +
    "\uffeb\041\uffeb\042\uffeb\046\uffeb\053\uffeb\070\uffeb\001\002" +
    "\000\004\043\042\001\002\000\036\005\uffe9\006\uffe9\010" +
    "\uffe9\012\uffe9\014\uffe9\016\uffe9\020\uffe9\022\uffe9\024\uffe9" +
    "\041\uffe9\042\uffe9\046\uffe9\053\uffe9\070\uffe9\001\002\000" +
    "\006\025\045\030\046\001\002\000\006\025\uffe0\030\uffe0" +
    "\001\002\000\036\005\uffe1\006\uffe1\010\uffe1\012\uffe1\014" +
    "\uffe1\016\uffe1\020\uffe1\022\uffe1\024\uffe1\041\uffe1\042\uffe1" +
    "\046\uffe1\053\uffe1\070\uffe1\001\002\000\006\054\052\055" +
    "\047\001\002\000\004\067\117\001\002\000\010\054\052" +
    "\055\047\071\055\001\002\000\010\054\uffdc\055\uffdc\071" +
    "\uffdc\001\002\000\004\067\053\001\002\000\004\072\054" +
    "\001\002\000\010\054\uffdb\055\uffdb\071\uffdb\001\002\000" +
    "\004\032\057\001\002\000\010\054\uffdd\055\uffdd\071\uffdd" +
    "\001\002\000\014\054\070\062\064\063\065\064\071\065" +
    "\072\001\002\000\006\031\063\032\057\001\002\000\006" +
    "\031\uffd8\032\uffd8\001\002\000\006\031\uffd9\032\uffd9\001" +
    "\002\000\006\025\uffde\030\uffde\001\002\000\004\067\115" +
    "\001\002\000\004\067\113\001\002\000\016\054\070\062" +
    "\064\063\065\064\071\065\072\071\101\001\002\000\016" +
    "\054\uffd5\062\uffd5\063\uffd5\064\uffd5\065\uffd5\071\uffd5\001" +
    "\002\000\004\067\077\001\002\000\004\067\075\001\002" +
    "\000\004\067\073\001\002\000\004\072\074\001\002\000" +
    "\016\054\uffd0\062\uffd0\063\uffd0\064\uffd0\065\uffd0\071\uffd0" +
    "\001\002\000\004\072\076\001\002\000\016\054\uffd1\062" +
    "\uffd1\063\uffd1\064\uffd1\065\uffd1\071\uffd1\001\002\000\004" +
    "\072\100\001\002\000\016\054\uffd2\062\uffd2\063\uffd2\064" +
    "\uffd2\065\uffd2\071\uffd2\001\002\000\010\033\uffcd\034\105" +
    "\072\103\001\002\000\016\054\uffd6\062\uffd6\063\uffd6\064" +
    "\uffd6\065\uffd6\071\uffd6\001\002\000\004\033\uffcf\001\002" +
    "\000\004\033\uffce\001\002\000\004\066\110\001\002\000" +
    "\004\033\107\001\002\000\006\031\uffd7\032\uffd7\001\002" +
    "\000\004\035\uffcb\001\002\000\004\035\112\001\002\000" +
    "\004\033\uffcc\001\002\000\004\072\114\001\002\000\016" +
    "\054\uffd3\062\uffd3\063\uffd3\064\uffd3\065\uffd3\071\uffd3\001" +
    "\002\000\004\072\116\001\002\000\016\054\uffd4\062\uffd4" +
    "\063\uffd4\064\uffd4\065\uffd4\071\uffd4\001\002\000\004\072" +
    "\120\001\002\000\010\054\uffda\055\uffda\071\uffda\001\002" +
    "\000\004\002\uffc4\001\002\000\036\005\ufff1\006\ufff1\010" +
    "\ufff1\012\ufff1\014\ufff1\016\ufff1\020\ufff1\022\ufff1\024\ufff1" +
    "\041\ufff1\042\ufff1\046\ufff1\053\ufff1\070\ufff1\001\002\000" +
    "\004\017\124\001\002\000\036\005\uffea\006\uffea\010\uffea" +
    "\012\uffea\014\uffea\016\uffea\020\uffea\022\uffea\024\uffea\041" +
    "\uffea\042\uffea\046\uffea\053\uffea\070\uffea\001\002\000\004" +
    "\013\126\001\002\000\036\005\uffed\006\uffed\010\uffed\012" +
    "\uffed\014\uffed\016\uffed\020\uffed\022\uffed\024\uffed\041\uffed" +
    "\042\uffed\046\uffed\053\uffed\070\uffed\001\002\000\004\074" +
    "\134\001\002\000\006\023\uffe3\026\uffe3\001\002\000\006" +
    "\023\133\026\127\001\002\000\006\023\uffe4\026\uffe4\001" +
    "\002\000\036\005\uffe5\006\uffe5\010\uffe5\012\uffe5\014\uffe5" +
    "\016\uffe5\020\uffe5\022\uffe5\024\uffe5\041\uffe5\042\uffe5\046" +
    "\uffe5\053\uffe5\070\uffe5\001\002\000\004\027\135\001\002" +
    "\000\006\023\uffe2\026\uffe2\001\002\000\004\047\137\001" +
    "\002\000\036\005\uffe8\006\uffe8\010\uffe8\012\uffe8\014\uffe8" +
    "\016\uffe8\020\uffe8\022\uffe8\024\uffe8\041\uffe8\042\uffe8\046" +
    "\uffe8\053\uffe8\070\uffe8\001\002\000\004\007\141\001\002" +
    "\000\036\005\uffef\006\uffef\010\uffef\012\uffef\014\uffef\016" +
    "\uffef\020\uffef\022\uffef\024\uffef\041\uffef\042\uffef\046\uffef" +
    "\053\uffef\070\uffef\001\002\000\004\011\143\001\002\000" +
    "\036\005\uffee\006\uffee\010\uffee\012\uffee\014\uffee\016\uffee" +
    "\020\uffee\022\uffee\024\uffee\041\uffee\042\uffee\046\uffee\053" +
    "\uffee\070\uffee\001\002\000\004\015\145\001\002\000\036" +
    "\005\uffec\006\uffec\010\uffec\012\uffec\014\uffec\016\uffec\020" +
    "\uffec\022\uffec\024\uffec\041\uffec\042\uffec\046\uffec\053\uffec" +
    "\070\uffec\001\002\000\030\006\023\010\022\012\027\014" +
    "\021\016\031\020\035\022\026\024\033\041\147\042\034" +
    "\046\024\001\002\000\004\002\uffc5\001\002\000\006\006" +
    "\uffc7\037\uffc7\001\002\000\004\071\155\001\002\000\006" +
    "\006\151\037\154\001\002\000\006\006\uffc8\037\uffc8\001" +
    "\002\000\004\002\uffc9\001\002\000\026\006\023\010\022" +
    "\012\027\014\021\016\031\020\035\022\026\024\033\042" +
    "\034\046\024\001\002\000\030\006\023\010\022\012\027" +
    "\014\021\016\031\020\035\022\026\024\033\042\034\046" +
    "\024\070\157\001\002\000\004\007\160\001\002\000\006" +
    "\006\uffc6\037\uffc6\001\002\000\016\054\163\056\165\057" +
    "\167\060\164\061\166\071\202\001\002\000\016\054\ufff7" +
    "\056\ufff7\057\ufff7\060\ufff7\061\ufff7\071\ufff7\001\002\000" +
    "\004\067\200\001\002\000\004\067\176\001\002\000\004" +
    "\067\174\001\002\000\004\067\172\001\002\000\004\067" +
    "\170\001\002\000\004\072\171\001\002\000\016\054\ufff4" +
    "\056\ufff4\057\ufff4\060\ufff4\061\ufff4\071\ufff4\001\002\000" +
    "\004\072\173\001\002\000\016\054\ufff2\056\ufff2\057\ufff2" +
    "\060\ufff2\061\ufff2\071\ufff2\001\002\000\004\072\175\001" +
    "\002\000\016\054\ufff5\056\ufff5\057\ufff5\060\ufff5\061\ufff5" +
    "\071\ufff5\001\002\000\004\072\177\001\002\000\016\054" +
    "\ufff3\056\ufff3\057\ufff3\060\ufff3\061\ufff3\071\ufff3\001\002" +
    "\000\004\072\201\001\002\000\016\054\ufff6\056\ufff6\057" +
    "\ufff6\060\ufff6\061\ufff6\071\ufff6\001\002\000\026\006\023" +
    "\010\022\012\027\014\021\016\031\020\035\022\026\024" +
    "\033\042\034\046\024\001\002\000\016\054\ufff8\056\ufff8" +
    "\057\ufff8\060\ufff8\061\ufff8\071\ufff8\001\002\000\030\005" +
    "\205\006\023\010\022\012\027\014\021\016\031\020\035" +
    "\022\026\024\033\042\034\046\024\001\002\000\004\002" +
    "\ufff9\001\002\000\004\002\001\001\002\000\004\074\223" +
    "\001\002\000\004\074\221\001\002\000\004\071\215\001" +
    "\002\000\004\051\214\001\002\000\004\051\uffc0\001\002" +
    "\000\004\002\uffc3\001\002\000\026\006\023\010\022\012" +
    "\027\014\021\016\031\020\035\022\026\024\033\042\034" +
    "\046\024\001\002\000\030\006\023\010\022\012\027\014" +
    "\021\016\031\020\035\022\026\024\033\042\034\046\024" +
    "\070\217\001\002\000\004\047\220\001\002\000\004\051" +
    "\uffca\001\002\000\004\045\222\001\002\000\004\051\uffc2" +
    "\001\002\000\004\027\224\001\002\000\004\051\uffc1\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\222\000\022\003\006\004\010\005\004\006\015\032" +
    "\011\035\007\040\014\041\003\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\036\212\037\211\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\007\160\010\161\001\001\000\006\033" +
    "\151\034\147\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\011\145\012\035\013\024\016\027\001\001\000" +
    "\012\011\031\012\035\013\024\016\027\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\014\130\015\127\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\012\121\013\024\016\027\001\001\000\004\017\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\043\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\021\047\022\050\001\001" +
    "\000\002\001\001\000\004\022\055\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\023\057\024\060\001\001\000\002\001\001\000" +
    "\006\025\065\026\066\001\001\000\004\024\061\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\026\101\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\027\105\030\103\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\031\110\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\015\131\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\012\121\013\024\016\027\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\034" +
    "\152\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\011\155\012\035\013\024\016\027\001\001\000\010\012" +
    "\121\013\024\016\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\202\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\011\203\012\035" +
    "\013\024\016\027\001\001\000\002\001\001\000\010\012" +
    "\121\013\024\016\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\011\215\012\035\013\024\016\027\001\001\000" +
    "\010\012\121\013\024\016\027\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ServidorAParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ServidorAParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ServidorAParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automaticamente ante algun error sintáctico.*/
    public void syntax_error(Symbol s)
    {
        //Metodos.addError("sintactico", (s.right+1), s.left, "Identificador \"" +s.value + "\" no reconocido por la gramatica");
        System.out.println("Error sintactico en la Fila " + (s.right+1) +" Columna "+s.left+ ". Identificador \"" +s.value + "\" no reconocido." );
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores.*/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    { 
        //Metodos.addError("sintactico", (s.right+1), s.left, "Identificador \"" +s.value + "\" no reconocido por la gramatica");
        System.out.println("Error sintactico en la Fila " + (s.right+1)+ " Columna "+s.left+". Identificador \"" + s.value + "\" no reconocido."); 
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ServidorAParser$actions {


    int nvl = 0;
    String nombreArchivo ="";

  private final ServidorAParser parser;

  /** Constructor */
  CUP$ServidorAParser$actions(ServidorAParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ServidorAParser$do_action(
    int                        CUP$ServidorAParser$act_num,
    java_cup.runtime.lr_parser CUP$ServidorAParser$parser,
    java.util.Stack            CUP$ServidorAParser$stack,
    int                        CUP$ServidorAParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ServidorAParser$result;

      /* select the action based on the action number */
      switch (CUP$ServidorAParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // CAMPOS_SOLICITUD ::= EMISOR 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(29/*CAMPOS_SOLICITUD*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // CAMPOS_SOLICITUD ::= tsdestinatario tcadcampo tedestinatario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(29/*CAMPOS_SOLICITUD*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // CAMPOS_SOLICITUD ::= tsrespuesta tcadcampo terespuesta 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(29/*CAMPOS_SOLICITUD*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // SOLICITUD ::= tssolicitudamistad CAMPOS_SOLICITUD tesolicitudamistad 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(31/*SOLICITUD*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // MENSAJE ::= tsmensaje LISTA_CAMPOS temensaje 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(30/*MENSAJE*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // LOGIN ::= tslogin LISTA_CAMPOS telogin 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(27/*LOGIN*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // USUARIO ::= tsusuario tmayor LISTA_CAMPOS tmenor teusuario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(26/*USUARIO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // LISTA_USUARIOS ::= USUARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(25/*LISTA_USUARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // LISTA_USUARIOS ::= LISTA_USUARIOS USUARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(25/*LISTA_USUARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // USUARIOS ::= tsusuarios LISTA_USUARIOS teusuarios 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(24/*USUARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // EMISOR ::= tsemisor tmayor LISTA_CAMPOS tmenor teemisor 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(28/*EMISOR*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // INSTRUCCIONES ::= tinstrucciones 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(23/*INSTRUCCIONES*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // FORMULA ::= tsformula INSTRUCCIONES teformula 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(22/*FORMULA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // CONTENIDO_CELDA ::= 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(21/*CONTENIDO_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // CONTENIDO_CELDA ::= FORMULA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(21/*CONTENIDO_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // CONTENIDO_CELDA ::= tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(21/*CONTENIDO_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ATRIBUTOS_CELDA ::= tformula tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // ATRIBUTOS_CELDA ::= tcolor tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // ATRIBUTOS_CELDA ::= ttipo tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // ATRIBUTOS_CELDA ::= tcolumna tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // ATRIBUTOS_CELDA ::= tfila tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(20/*ATRIBUTOS_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // LISTA_ATR_CELDA ::= ATRIBUTOS_CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(19/*LISTA_ATR_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // LISTA_ATR_CELDA ::= LISTA_ATR_CELDA ATRIBUTOS_CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(19/*LISTA_ATR_CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // CELDA ::= tscelda LISTA_ATR_CELDA tmayor CONTENIDO_CELDA tecelda 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(18/*CELDA*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // LISTA_CELDAS ::= CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(17/*LISTA_CELDAS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // LISTA_CELDAS ::= LISTA_CELDAS CELDA 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(17/*LISTA_CELDAS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // ATRIBUTO_ARCHIVO ::= ttama tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(16/*ATRIBUTO_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // ATRIBUTO_ARCHIVO ::= ttipo tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(16/*ATRIBUTO_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // LISTA_ATR_ARCHIVO ::= ATRIBUTO_ARCHIVO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(15/*LISTA_ATR_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // LISTA_ATR_ARCHIVO ::= LISTA_ATR_ARCHIVO ATRIBUTO_ARCHIVO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(15/*LISTA_ATR_ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // ARCHIVO ::= tsarchivo LISTA_ATR_ARCHIVO tmayor LISTA_CELDAS tearchivo 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(14/*ARCHIVO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // LISTA_ARCHIVOS ::= 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(13/*LISTA_ARCHIVOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // LISTA_ARCHIVOS ::= LISTA_ARCHIVOS ARCHIVO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(13/*LISTA_ARCHIVOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ARCHIVOS ::= tsarchivos LISTA_ARCHIVOS tearchivos 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(12/*ARCHIVOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // DESTINATARIO ::= tsdestinatario tcadcampo tedestinatario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(11/*DESTINATARIO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // LISTA_DESTINATARIOS ::= DESTINATARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(10/*LISTA_DESTINATARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // LISTA_DESTINATARIOS ::= LISTA_DESTINATARIOS DESTINATARIO 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(10/*LISTA_DESTINATARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // DESTINATARIOS ::= tsdestinatarios LISTA_DESTINATARIOS tedestinatarios 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(9/*DESTINATARIOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // CAMPOS ::= ARCHIVOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // CAMPOS ::= DESTINATARIOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // CAMPOS ::= tsemisor tcadcampo teemisor 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // CAMPOS ::= tsestado tcadcampo teestado 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // CAMPOS ::= tsasunto tcadcampo teasunto 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // CAMPOS ::= tscontenido tcadcampo tecontenido 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // CAMPOS ::= tsclave tcadcampo teclave 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // CAMPOS ::= tsnombre tcadcampo tenombre 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CAMPOS ::= tsfecha tfechacadena tefecha 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CAMPOS ::= tsusuario tcadcampo teusuario 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(8/*CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // LISTA_CAMPOS ::= CAMPOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(7/*LISTA_CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // LISTA_CAMPOS ::= LISTA_CAMPOS CAMPOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(7/*LISTA_CAMPOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ATRIBUTO_SESION ::= tfecha tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ATRIBUTO_SESION ::= tde tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ATRIBUTO_SESION ::= tpeticion tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ATRIBUTO_SESION ::= tid tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ATRIBUTO_SESION ::= ttipo tigual tcadena 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(6/*ATRIBUTO_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // LISTA_ATR_SESION ::= ATRIBUTO_SESION 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(5/*LISTA_ATR_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // LISTA_ATR_SESION ::= LISTA_ATR_SESION ATRIBUTO_SESION 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(5/*LISTA_ATR_SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SESION ::= tssesion LISTA_ATR_SESION tmayor LISTA_CAMPOS tesesion 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(4/*SESION*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ELEMENTOS ::= MENSAJE 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ELEMENTOS ::= SOLICITUD 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // ELEMENTOS ::= LOGIN 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // ELEMENTOS ::= USUARIOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ELEMENTOS ::= SESION 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(3/*ELEMENTOS*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CUERPO ::= ELEMENTOS 
            {
              Object RESULT = null;

              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(2/*CUERPO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CUERPO 
            {
              Object RESULT = null;
		 System.out.println("Fin"); 
              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          return CUP$ServidorAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).value;
		RESULT = start_val;
              CUP$ServidorAParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$ServidorAParser$stack.elementAt(CUP$ServidorAParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$ServidorAParser$parser.done_parsing();
          return CUP$ServidorAParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

