
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 21 05:08:56 CST 2014
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class SymServidorA {
  /* terminals */
  public static final int tssolicitudamistad = 38;
  public static final int tsemisor = 36;
  public static final int ttama = 43;
  public static final int tsmensaje = 40;
  public static final int tigual = 53;
  public static final int tsclave = 10;
  public static final int telogin = 31;
  public static final int tscontenido = 14;
  public static final int teusuario = 5;
  public static final int tearchivo = 23;
  public static final int teasunto = 13;
  public static final int tecontenido = 15;
  public static final int tsusuario = 4;
  public static final int tsasunto = 12;
  public static final int tid = 44;
  public static final int tsarchivo = 22;
  public static final int tcadena = 56;
  public static final int tslogin = 30;
  public static final int tmenor = 54;
  public static final int tformula = 51;
  public static final int tsrespuesta = 34;
  public static final int tcolor = 50;
  public static final int tcadcampo = 58;
  public static final int tmayor = 55;
  public static final int terespuesta = 35;
  public static final int EOF = 0;
  public static final int tsdestinatario = 20;
  public static final int error = 1;
  public static final int tfechacadena = 57;
  public static final int tcolumna = 49;
  public static final int tefecha = 7;
  public static final int tedestinatarios = 17;
  public static final int tsusuarios = 28;
  public static final int teestado = 33;
  public static final int tsarchivos = 18;
  public static final int teusuarios = 29;
  public static final int tsestado = 32;
  public static final int teformula = 27;
  public static final int tecelda = 25;
  public static final int tearchivos = 19;
  public static final int tpeticion = 45;
  public static final int tedestinatario = 21;
  public static final int tfila = 48;
  public static final int tsformula = 26;
  public static final int tesesion = 3;
  public static final int tssesion = 2;
  public static final int tsdestinatarios = 16;
  public static final int tsfecha = 6;
  public static final int tinstrucciones = 52;
  public static final int tscelda = 24;
  public static final int teclave = 11;
  public static final int tenombre = 9;
  public static final int tde = 46;
  public static final int tsnombre = 8;
  public static final int temensaje = 41;
  public static final int tfecha = 47;
  public static final int tesolicitudamistad = 39;
  public static final int ttipo = 42;
  public static final int teemisor = 37;
}

