
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 24 17:10:27 CST 2014
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class ClienteASym {
  /* terminals */
  public static final int tigual = 29;
  public static final int tmenorigual = 70;
  public static final int twhile = 77;
  public static final int tecorreo = 33;
  public static final int tcoma = 44;
  public static final int tinteger = 45;
  public static final int tearchivo = 17;
  public static final int tmod = 55;
  public static final int ttrue = 59;
  public static final int tentero = 56;
  public static final int tenombre = 9;
  public static final int tscelda = 18;
  public static final int tede = 35;
  public static final int ttipo = 22;
  public static final int tchar = 47;
  public static final int tesesion = 3;
  public static final int tmenos = 51;
  public static final int tmenor = 68;
  public static final int tsfecha = 6;
  public static final int tedestinatario = 15;
  public static final int tdiferente = 73;
  public static final int telse = 64;
  public static final int teformula = 21;
  public static final int tsasunto = 80;
  public static final int tfor = 74;
  public static final int tmas = 50;
  public static final int teenviado = 87;
  public static final int tlc = 63;
  public static final int tla = 62;
  public static final int treturn = 79;
  public static final int tmayorigual = 71;
  public static final int tboolean = 48;
  public static final int tcolor = 27;
  public static final int tpyc = 42;
  public static final int teregistro = 82;
  public static final int tsusuario = 4;
  public static final int tamperson = 36;
  public static final int tbegin = 40;
  public static final int tdividir = 53;
  public static final int tdecimal = 57;
  public static final int tfila = 25;
  public static final int tsarchivos = 12;
  public static final int tend = 41;
  public static final int tdospuntos = 43;
  public static final int tscorreo = 32;
  public static final int tcadcampo = 30;
  public static final int tcadena = 31;
  public static final int tsarchivo = 16;
  public static final int toper = 37;
  public static final int tsnombre = 8;
  public static final int tssesion = 2;
  public static final int tand = 66;
  public static final int tecontenido = 11;
  public static final int tigualigual = 72;
  public static final int EOF = 0;
  public static final int tpc = 39;
  public static final int tsde = 34;
  public static final int tstring = 49;
  public static final int tpa = 38;
  public static final int tmayor = 69;
  public static final int tcaracter = 58;
  public static final int tcolumna = 26;
  public static final int teasunto = 81;
  public static final int tor = 65;
  public static final int error = 1;
  public static final int tnext = 76;
  public static final int tiden = 78;
  public static final int tif = 61;
  public static final int teerror = 85;
  public static final int tsformula = 20;
  public static final int tid = 24;
  public static final int teusuario = 5;
  public static final int tfalse = 60;
  public static final int tfloat = 46;
  public static final int tsenviado = 86;
  public static final int tearchivos = 13;
  public static final int tecelda = 19;
  public static final int tpot = 54;
  public static final int tpor = 52;
  public static final int tno = 67;
  public static final int ttama = 23;
  public static final int tformula = 28;
  public static final int tto = 75;
  public static final int tefecha = 7;
  public static final int tsregistro = 83;
  public static final int tsdestinatario = 14;
  public static final int tscontenido = 10;
  public static final int tserror = 84;
}

