
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 27 18:01:39 CST 2014
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class ServidorASym {
  /* terminals */
  public static final int tfecha = 47;
  public static final int tigual = 52;
  public static final int tmenorigual = 102;
  public static final int twhile = 109;
  public static final int tcoma = 76;
  public static final int tecorreo = 58;
  public static final int tinteger = 77;
  public static final int tearchivo = 23;
  public static final int ttrue = 91;
  public static final int tmod = 87;
  public static final int tentero = 88;
  public static final int tenombre = 9;
  public static final int tscelda = 24;
  public static final int tede = 60;
  public static final int ttipo = 42;
  public static final int tchar = 79;
  public static final int tmenos = 83;
  public static final int tesesion = 3;
  public static final int tmenor = 100;
  public static final int tsfecha = 6;
  public static final int tedestinatario = 21;
  public static final int tdiferente = 105;
  public static final int telse = 96;
  public static final int teformula = 27;
  public static final int tfor = 106;
  public static final int tsasunto = 12;
  public static final int tmas = 82;
  public static final int tsdestinatarios = 16;
  public static final int tsemisor = 36;
  public static final int tlc = 95;
  public static final int tla = 94;
  public static final int treturn = 111;
  public static final int tmayorigual = 103;
  public static final int tboolean = 80;
  public static final int temensaje = 41;
  public static final int tcolor = 50;
  public static final int teestado = 33;
  public static final int tscorreos = 55;
  public static final int tpyc = 74;
  public static final int tsusuarios = 28;
  public static final int tsusuario = 4;
  public static final int tssolicitud = 66;
  public static final int terespuesta = 35;
  public static final int tamperson = 68;
  public static final int tbegin = 72;
  public static final int tusuario = 61;
  public static final int tdecimal = 89;
  public static final int tdividir = 85;
  public static final int tfila = 48;
  public static final int teclave = 11;
  public static final int tsarchivos = 18;
  public static final int tend = 73;
  public static final int tdospuntos = 75;
  public static final int tscorreo = 57;
  public static final int tcadcampo = 53;
  public static final int tcadena = 54;
  public static final int tsarchivo = 22;
  public static final int toper = 69;
  public static final int tsnombre = 8;
  public static final int tsdestino = 62;
  public static final int tssolicitudamistad = 38;
  public static final int tde = 46;
  public static final int tssesion = 2;
  public static final int tand = 98;
  public static final int tecontenido = 15;
  public static final int tigualigual = 104;
  public static final int tpeticion = 45;
  public static final int EOF = 0;
  public static final int tesolicitudes = 65;
  public static final int tpc = 71;
  public static final int tstring = 81;
  public static final int tsde = 59;
  public static final int tpa = 70;
  public static final int tsclave = 10;
  public static final int tmayor = 101;
  public static final int tcaracter = 90;
  public static final int tcolumna = 49;
  public static final int telogin = 31;
  public static final int tor = 97;
  public static final int teasunto = 13;
  public static final int error = 1;
  public static final int tnext = 108;
  public static final int tiden = 110;
  public static final int tsrespuesta = 34;
  public static final int tif = 93;
  public static final int tedestinatarios = 17;
  public static final int tsformula = 26;
  public static final int tid = 44;
  public static final int tesolicitudamistad = 39;
  public static final int teusuarios = 29;
  public static final int tsmensaje = 40;
  public static final int teusuario = 5;
  public static final int teemisor = 37;
  public static final int tsestado = 32;
  public static final int tfalse = 92;
  public static final int tfloat = 78;
  public static final int tearchivos = 19;
  public static final int tecelda = 25;
  public static final int tecorreos = 56;
  public static final int tpot = 86;
  public static final int tpor = 84;
  public static final int tesolicitud = 67;
  public static final int tno = 99;
  public static final int ttama = 43;
  public static final int tslogin = 30;
  public static final int tformula = 51;
  public static final int tto = 107;
  public static final int tefecha = 7;
  public static final int tsdestinatario = 20;
  public static final int tssolicitudes = 64;
  public static final int tscontenido = 14;
  public static final int tedestino = 63;
}

